"""Delegation clustering + subagent draft generation.

Clusters ``general-purpose`` agent invocations by their
``description + prompt`` text using TF-IDF → LSA → KMeans, then
synthesizes a draft subagent definition for each cluster. Output is a
list of ``DelegationSuggestion`` records that surface on
``DiagnosticsResult.delegation_suggestions``.

scikit-learn is an **optional extra** (``agentfluent[clustering]``).
Users who only run ``agentfluent analyze`` without clustering flags do
not need to install it. The top-level try/except sets
``SKLEARN_AVAILABLE``; direct callers of the public functions here
get a clear ``SklearnMissingError`` instead of an ImportError. The
pipeline silently skips clustering when unavailable; the CLI surfaces
an error + non-zero exit when a user explicitly passes a clustering
flag but the extra is missing.

See issue #139 for the plan to strip this conditional machinery once
a second sklearn-dependent feature lands.
"""

from __future__ import annotations

import logging
import re
import warnings
from collections import Counter
from dataclasses import dataclass
from typing import TYPE_CHECKING, Literal

# sklearn is an optional extra; module bodies that reference these
# names are only ever called via the SKLEARN_AVAILABLE gate. Leaving
# the names undefined when sklearn is missing matches the established
# pattern (see _clustering.py) — function-local attribute resolution
# means delegation.py still imports cleanly without sklearn installed.
try:
    import numpy as np
    from sklearn.decomposition import TruncatedSVD
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.metrics.pairwise import cosine_similarity
except ImportError:  # pragma: no cover — exercised via the install-path test
    pass

from agentfluent.agents.models import is_general_purpose
from agentfluent.diagnostics._clustering import (
    SKLEARN_AVAILABLE,
    SklearnMissingError,
    all_rows_identical,
    cluster_embeddings,
    group_indices_by_label,
    mean_pairwise_cosine,
    top_tfidf_terms,
)
from agentfluent.diagnostics._complexity import (
    MODEL_HAIKU,
    MODEL_OPUS,
    MODEL_SONNET,
    aggregate_cluster_stats,
    classify_complexity,
    recommend_model_for_complexity,
)
from agentfluent.diagnostics.models import DelegationSuggestion

if TYPE_CHECKING:
    from agentfluent.agents.models import AgentInvocation
    from agentfluent.config.models import AgentConfig

# Re-exported from _clustering so existing import paths keep working
# (e.g., ``from agentfluent.diagnostics.delegation import SKLEARN_AVAILABLE``,
# ``SklearnMissingError``, and ``monkeypatch.setattr(delegation, "SKLEARN_AVAILABLE", ...)``).
__all__ = [
    "DEFAULT_MIN_CLUSTER_SIZE",
    "DEFAULT_MIN_SIMILARITY",
    "DEFAULT_TOOL_FREQUENCY_THRESHOLD",
    "MIN_TEXT_TOKENS",
    "MODEL_HAIKU",
    "MODEL_OPUS",
    "MODEL_SONNET",
    "SKLEARN_AVAILABLE",
    "DelegationCluster",
    "SklearnMissingError",
    "cluster_delegations",
    "generate_draft",
    "suggest_delegations",
]

logger = logging.getLogger(__name__)

# Module-level tunables. Override via function kwargs or CLI flags.
# Threshold provenance and empirical validation: see
# `scripts/calibration/threshold_validation.ipynb` (#140). Current
# defaults are retained pending multi-contributor calibration data;
# every value below was reviewed against one contributor's dataset
# and kept for lack of clear signal to change it.
# MIN_TEXT_TOKENS is the combined (description + prompt) floor below
# which an invocation is dropped before clustering. Agent-to-agent
# delegations are generated by a parent agent, not a human typing
# "help me", so the realistic floor is well above an anti-noise guard
# value. #140's calibration observed nothing under 100 tokens on a
# one-contributor dataset; 50 preserves a safe margin while still
# filtering pathological inputs. Revisit alongside the sweep in
# `scripts/calibration/threshold_validation.ipynb` §1.
MIN_TEXT_TOKENS = 50
LSA_COMPONENTS = 50
DEFAULT_MIN_CLUSTER_SIZE = 5
DEFAULT_MIN_SIMILARITY = 0.7
# Confidence tier boundaries: calibrated against two real-world
# datasets (agentfluent: 5 clusters, cohesion 0.26–0.46; codefluent:
# 2 clusters, cohesion 0.16–0.31) in the #167 investigation. Clusters
# are genuinely finding task families, but free-text delegation
# prompts have enough variance that real-world cohesion rarely
# exceeds 0.5 even for coherent groupings. Semantic review:
# cohesion ≥ 0.35 reliably surfaces recognizable patterns (PR reviews,
# mode flags); below that lives loose thematic grouping that still
# warrants a REVIEW BEFORE USE caveat (#168's YAML draft warning).
_CONFIDENCE_HIGH_SIZE = 10
_CONFIDENCE_HIGH_COHESION = 0.50
_CONFIDENCE_MEDIUM_COHESION = 0.35
_PROMPT_BODY_SNIPPET_CHARS = 500

# Frequency threshold for the per-tool inclusion filter. A tool is
# kept on the draft's `tools` list only if it appears in at least this
# fraction of the cluster's member traces (presence-based, NOT call-
# count-based — one member running `Bash` 50 times still counts as a
# single member). Default 0.5 per #184 architect review: presence
# gives the least-privilege answer in every uneven-call-volume case
# (the exact pathology #184 was filed to fix). Calibration sweep is
# tracked in `scripts/calibration/threshold_validation.ipynb` (#140).
DEFAULT_TOOL_FREQUENCY_THRESHOLD = 0.5

# MODEL_HAIKU/SONNET/OPUS are re-exported from _complexity.py — see #185
# for the consolidation. Pre-#185 they lived here directly.


@dataclass
class DelegationCluster:
    """Internal: a KMeans cluster of general-purpose invocations."""

    members: list[AgentInvocation]
    top_terms: list[str]
    cohesion_score: float


ConfidenceTier = Literal["high", "medium", "low"]


def _require_sklearn() -> None:
    if not SKLEARN_AVAILABLE:
        raise SklearnMissingError(
            "Install agentfluent[clustering] to enable delegation analysis.",
        )


def _combined_text(inv: AgentInvocation) -> str:
    return f"{inv.description} {inv.prompt}"


def _combined_text_tokens(inv: AgentInvocation) -> int:
    return len(_combined_text(inv).split())


def _filter_candidates(
    invocations: list[AgentInvocation],
) -> list[AgentInvocation]:
    """Keep general-purpose invocations with enough text to cluster on."""
    return [
        inv for inv in invocations
        if is_general_purpose(inv.agent_type)
        and _combined_text_tokens(inv) >= MIN_TEXT_TOKENS
    ]


def _count_clusterable_invocations(invocations: list[AgentInvocation]) -> int:
    """Count general-purpose invocations eligible for clustering.

    Used by the diagnostics pipeline to distinguish "insufficient
    invocations" from "clustering produced nothing" when populating
    ``delegation_suggestions_skipped_reason``.
    """
    return len(_filter_candidates(invocations))


def _build_single_cluster(
    candidates: list[AgentInvocation],
    tfidf_matrix: np.ndarray,
    terms: np.ndarray,
) -> DelegationCluster:
    """Build one cluster holding every candidate — the answer when
    every TF-IDF row is identical. Cohesion is 1.0 by definition
    (all members share the same vector)."""
    all_indices = list(range(len(candidates)))
    return DelegationCluster(
        members=list(candidates),
        top_terms=top_tfidf_terms(tfidf_matrix, all_indices, terms),
        cohesion_score=1.0,
    )


def cluster_delegations(
    invocations: list[AgentInvocation],
    *,
    min_cluster_size: int = DEFAULT_MIN_CLUSTER_SIZE,
) -> list[DelegationCluster]:
    """Group general-purpose invocations into clusters of similar delegations.

    Raises ``SklearnMissingError`` when scikit-learn is not installed.
    Returns ``[]`` if there are not enough candidates or all are filtered
    out by the minimum-text-length guard.
    """
    _require_sklearn()

    candidates = _filter_candidates(invocations)
    if len(candidates) < min_cluster_size:
        return []

    texts = [_combined_text(inv) for inv in candidates]
    tfidf = TfidfVectorizer(stop_words="english", max_features=500)
    tfidf_matrix = tfidf.fit_transform(texts)
    terms = tfidf.get_feature_names_out()

    # Anomaly: if every row is identical, surface the upstream issue and
    # return a single cluster. Clustering algorithms below would either
    # emit confusing convergence warnings or silently produce no output.
    if all_rows_identical(tfidf_matrix):
        logger.warning(
            "Delegation clustering: all %d TF-IDF rows are identical — "
            "this is unusual for real agent data. Check for duplicate "
            "invocation records or upstream extraction bugs.",
            tfidf_matrix.shape[0],
        )
        return [_build_single_cluster(candidates, tfidf_matrix, terms)]

    # LSA dimensionality reduction — skip gracefully if we do not have
    # enough features or samples to support TruncatedSVD.
    n_components = min(
        LSA_COMPONENTS, tfidf_matrix.shape[1] - 1, len(candidates) - 1,
    )
    if n_components >= 2:
        with warnings.catch_warnings():
            # TruncatedSVD can raise a RuntimeWarning on near-zero
            # variance input; the degenerate-fallback in
            # cluster_embeddings already handles the output path.
            warnings.simplefilter("ignore", category=RuntimeWarning)
            lsa = TruncatedSVD(n_components=n_components, random_state=42)
            embeddings = lsa.fit_transform(tfidf_matrix)
    else:
        embeddings = tfidf_matrix.toarray()

    labels = cluster_embeddings(embeddings, len(candidates))
    groups = group_indices_by_label(labels)

    clusters: list[DelegationCluster] = []
    for _label, member_indices in sorted(groups.items()):
        if len(member_indices) < min_cluster_size:
            continue
        members = [candidates[i] for i in member_indices]
        member_embeddings = embeddings[member_indices]
        cohesion = mean_pairwise_cosine(member_embeddings)
        top_terms = top_tfidf_terms(tfidf_matrix, member_indices, terms)
        clusters.append(
            DelegationCluster(
                members=members,
                top_terms=top_terms,
                cohesion_score=cohesion,
            ),
        )
    return clusters


_SLUG_STRIP_RE = re.compile(r"[^a-z0-9-]")

_NAME_STOPWORD_RE = re.compile(
    r"^(?:\d+|v\d+|[0-9a-f]{7,})$",
)
"""Tokens that look like accidental identifiers rather than reusable
workflow terms (#345). Run against the slug-sanitized form (lowercase,
non-``[a-z0-9-]`` stripped — so ``v0.6`` arrives as ``v06`` and matches
``^v\\d+$``). Three alternatives:

* pure-numeric — issue/PR numbers, occasionally HTTP status codes (TF-IDF
  co-occurrence keeps companion terms descriptive in the latter case);
* ``v``-prefix numeric — version refs like ``v0``, ``v06`` (post-slug
  ``v0.6``), ``v1``;
* seven-plus hex chars — SHA-prefix tokens.

Filter applies only to cluster auto-naming. ``synthesize_description``,
``_synthesize_prompt``, and the JSON ``top_terms`` array stay raw so a
human / CI consumer can still see the unfiltered signal."""


def synthesize_name(top_terms: list[str]) -> str:
    """Build a kebab-case agent name from the top TF-IDF terms.

    Prefers the first two terms when available; otherwise falls back to
    a generic placeholder. Not unique across clusters — the caller is
    expected to show these as *drafts*, not final names.

    Stopword filter runs after slug sanitization (so ``v0.6`` lowercase
    is matched directly, and ``272`` survives ``_SLUG_STRIP_RE``
    unchanged) but before first-two selection — getting the order wrong
    produces empty names or wrong terms.
    """
    cleaned: list[str] = []
    for term in top_terms:
        slug = _SLUG_STRIP_RE.sub("", term.lower().replace("_", "-"))
        if not slug:
            continue
        if _NAME_STOPWORD_RE.match(slug):
            continue
        cleaned.append(slug)
    if not cleaned:
        return "custom-agent"
    if len(cleaned) == 1:
        return cleaned[0]
    return f"{cleaned[0]}-{cleaned[1]}"


def synthesize_description(top_terms: list[str]) -> str:
    if not top_terms:
        return "Handles a recurring delegation pattern."
    terms_list = ", ".join(top_terms[:3])
    return f"Handles delegations related to: {terms_list}."


def _synthesize_prompt(top_terms: list[str], members: list[AgentInvocation]) -> str:
    """Generic prompt scaffold anchored on the cluster's top terms.

    Intentionally minimal — users will refine before committing. The
    scaffold references the top terms so it feels purposeful rather
    than boilerplate.
    """
    terms_list = ", ".join(top_terms[:3]) if top_terms else "this task"
    example_descs = [m.description for m in members[:2] if m.description]
    examples_block = ""
    if example_descs:
        examples_block = "\n\nExample delegations observed:\n" + "\n".join(
            f"- {d}" for d in example_descs
        )
    return (
        f"You handle recurring delegations involving {terms_list}.\n\n"
        "Scope your work to the specific task described in the user's "
        "prompt. Return concise, structured output."
        f"{examples_block}"
    )


def _tool_presence_counts(members: list[AgentInvocation]) -> Counter[str]:
    """Per-tool count of how many cluster members used that tool at least once.

    Shared primitive for ``_collect_tools_from_traces`` (sort the keys)
    and ``_filter_tools_by_frequency`` (apply the cutoff). Members
    without a linked trace contribute nothing here, but still count in
    the denominator at the filter site — see ``_filter_tools_by_frequency``.
    """
    counts: Counter[str] = Counter()
    for m in members:
        if m.trace is not None:
            counts.update(m.trace.unique_tool_names)
    return counts


def _collect_tools_from_traces(members: list[AgentInvocation]) -> list[str]:
    """Sorted union of every tool observed across the cluster's traces."""
    return sorted(_tool_presence_counts(members))


def _filter_tools_by_frequency(
    members: list[AgentInvocation],
    *,
    threshold: float = DEFAULT_TOOL_FREQUENCY_THRESHOLD,
) -> list[str]:
    """Keep tools used in at least ``threshold`` fraction of cluster members.

    Presence-based: a tool counts once per member that used it,
    regardless of call volume within that member. This is the
    least-privilege answer when call volume is uneven (one member
    running ``Bash`` 50 times shouldn't keep ``Bash`` on the draft for
    a 5-member cluster where 4 members never touched it). See #184 for
    the architect-reviewed rationale.

    Members without a linked trace are still counted in the denominator
    — they contribute zero observed tools, which lowers every tool's
    presence ratio. That's intentional: a half-traced cluster shouldn't
    over-recommend tools based on the observed half.
    """
    if not members:
        return []
    counts = _tool_presence_counts(members)
    cutoff = threshold * len(members)
    return sorted(t for t, c in counts.items() if c >= cutoff)


def _classify_model(tools: list[str], members: list[AgentInvocation]) -> str:
    """Pick a model tier for a delegation cluster via the unified classifier.

    Pre-#185, this used a delegation-local heuristic that could disagree
    with model_routing's diagnostic on the same workload (see #185 for
    the example that motivated the consolidation). Now both paths route
    through ``classify_complexity`` in ``diagnostics/_complexity``.
    """
    stats = aggregate_cluster_stats(members, tools=tools)
    return recommend_model_for_complexity(classify_complexity(stats))


def _classify_confidence(cluster_size: int, cohesion: float) -> ConfidenceTier:
    if cluster_size >= _CONFIDENCE_HIGH_SIZE and cohesion >= _CONFIDENCE_HIGH_COHESION:
        return "high"
    if cohesion >= _CONFIDENCE_MEDIUM_COHESION:
        return "medium"
    return "low"


def generate_draft(cluster: DelegationCluster) -> DelegationSuggestion:
    """Synthesize a draft subagent definition from a cluster.

    ``tools`` is the frequency-filtered list (presence in
    ``DEFAULT_TOOL_FREQUENCY_THRESHOLD`` of members) — the
    least-privilege set used in the YAML frontmatter. ``tools_observed``
    is the full union; users widening the draft can consult it. See
    #184 for the rationale and architect review.
    """
    tools_observed = _collect_tools_from_traces(cluster.members)
    tools = _filter_tools_by_frequency(cluster.members)
    if not tools_observed:
        tools_note = "# run with newer session data for tool recommendations"
    elif not tools:
        tools_note = (
            f"# no tool used in >="
            f"{int(DEFAULT_TOOL_FREQUENCY_THRESHOLD * 100)}% of cluster members "
            f"— see tools_observed for the unfiltered list"
        )
    else:
        tools_note = ""
    return DelegationSuggestion(
        name=synthesize_name(cluster.top_terms),
        description=synthesize_description(cluster.top_terms),
        model=_classify_model(tools, cluster.members),
        tools=tools,
        tools_observed=tools_observed,
        tools_note=tools_note,
        prompt_template=_synthesize_prompt(cluster.top_terms, cluster.members),
        confidence=_classify_confidence(len(cluster.members), cluster.cohesion_score),
        cluster_size=len(cluster.members),
        cohesion_score=cluster.cohesion_score,
        top_terms=list(cluster.top_terms),
    )


def _config_text(config: AgentConfig) -> str:
    """Pick the text to dedup against: description, or prompt_body snippet.

    ``AgentConfig.description`` is often empty in real configs (YAML
    frontmatter isn't always populated). Fall back to a prompt_body
    prefix so dedup still finds obvious overlaps.
    """
    if config.description:
        return config.description
    return config.prompt_body[:_PROMPT_BODY_SNIPPET_CHARS]


def apply_dedup(
    drafts: list[DelegationSuggestion],
    existing_configs: list[AgentConfig],
    min_similarity: float,
) -> list[DelegationSuggestion]:
    """Mark drafts whose description+prompt is too close to any existing
    agent config. Deduped drafts are NOT removed from the output — they
    ship with a ``dedup_note`` so users see what was suppressed and why.
    """
    if not existing_configs:
        return drafts
    draft_texts = [f"{d.description} {d.prompt_template}" for d in drafts]
    config_texts = [_config_text(c) for c in existing_configs]
    # TF-IDF needs at least one non-empty text per document; skip dedup
    # entirely if all the config texts are empty.
    if not any(t.strip() for t in config_texts):
        return drafts
    vectorizer = TfidfVectorizer(stop_words="english")
    corpus = draft_texts + config_texts
    matrix = vectorizer.fit_transform(corpus)
    draft_vecs = matrix[: len(drafts)]
    config_vecs = matrix[len(drafts) :]
    sim = cosine_similarity(draft_vecs, config_vecs)
    for i, draft in enumerate(drafts):
        if sim.shape[1] == 0:
            break
        max_j = int(sim[i].argmax())
        max_sim = float(sim[i][max_j])
        if max_sim > min_similarity:
            matched_name = existing_configs[max_j].name
            draft.matched_agent = matched_name
            draft.dedup_note = (
                f"suppressed — already covered by '{matched_name}' "
                f"(similarity {max_sim:.2f})"
            )
    return drafts


def suggest_delegations(
    invocations: list[AgentInvocation],
    *,
    existing_configs: list[AgentConfig] | None = None,
    min_cluster_size: int = DEFAULT_MIN_CLUSTER_SIZE,
    min_similarity: float = DEFAULT_MIN_SIMILARITY,
) -> list[DelegationSuggestion]:
    """End-to-end: cluster + draft + dedup → list of DelegationSuggestion.

    Raises ``SklearnMissingError`` when scikit-learn is not installed.
    """
    _require_sklearn()
    clusters = cluster_delegations(
        invocations, min_cluster_size=min_cluster_size,
    )
    if not clusters:
        return []
    drafts = [generate_draft(c) for c in clusters]
    if existing_configs:
        drafts = apply_dedup(drafts, existing_configs, min_similarity)
    return drafts
